# Generated by Django 2.1.7 on 2019-03-02 11:27

from django.db import migrations, models
import tweets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(max_length=140, validators=[tweets.models.validate_content]),
        ),
    ]
