# Generated by Django 2.1.7 on 2019-03-03 13:16

from django.db import migrations, models
import tweets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20190302_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(validators=[tweets.validators.validate_content]),
        ),
    ]
