# Generated by Django 2.1.7 on 2019-03-03 15:06

from django.db import migrations, models
import tweets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20190303_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(max_length=140, validators=[tweets.validators.validate_content]),
        ),
    ]
